// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";
  var expect;

  expect = chai.expect;

  describe('Variable', function() {
    var variable;

    variable = null;
    beforeEach(function() {
      return variable = new Variable();
    });
    afterEach(function() {
      return variable = null;
    });
    it("should create a varable correctly", function() {
      expect(variable).to.exist;
      expect(variable.get('c')).is.equal(0.0000001);
      expect(variable.get('a')).is.equal(0.0001);
      expect(variable.get('v')).is.equal(0.01);
      return expect(variable.get('d')).is.equal(0.1);
    });
    it("should create a varable correctly when overriding defaults", function() {
      var variable1;

      variable1 = new Variable({
        'd': 4,
        'v': 3,
        'a': 2,
        'c': 1
      });
      expect(variable1.get('c')).is.equal(1);
      expect(variable1.get('a')).is.equal(2);
      expect(variable1.get('v')).is.equal(3);
      return expect(variable1.get('d')).is.equal(4);
    });
    it("should be able to mutate", function() {
      variable.mutate();
      expect(variable.get('a')).is.above(0.0001 - 0.0000001).and.below(0.0001 + 0.0000001).and.is.not.equal(0.0001);
      expect(variable.get('v')).is.above(0.01 - 0.0001).and.below(0.01 + 0.0001).and.is.not.equal(0.01);
      return expect(variable.get('d')).is.above(0.1 - 0.01).and.below(0.1 + 0.01).and.is.not.equal(0.100);
    });
    return it("should be able to create custom variables with JSON, will be needed for persistanse later");
  });

  describe("Agent", function() {
    return describe("initialize", function() {
      var agent;

      agent = null;
      beforeEach(function() {
        return agent = new Agent();
      });
      afterEach(function() {
        return agent = null;
      });
      it("should be defined when created", function() {
        return expect(agent).to.exist;
      });
      it("should create Health Points", function() {
        expect(agent.get('healthPoints')).to.exist;
        return expect(agent.get('healthPoints')).is.equal(20);
      });
      it("should make healthPoints equal to the starting constant", function() {
        var agent1;

        agent1 = new Agent({
          'healthPoints': 100
        });
        return expect(agent1.get('healthPoints')).is.equal(agent.get('startingHealthPoints'));
      });
      it("should add health points", function() {
        agent.changeHealth(5);
        return expect(agent.get('healthPoints')).is.equal(25);
      });
      it("should subtract health points", function() {
        agent.changeHealth(-5);
        return expect(agent.get('healthPoints')).is.equal(15);
      });
      describe("linkUtil", function() {
        it("should create linkUtil Node", function() {
          return expect(agent.get('linkUtil')).to.exist;
        });
        it("should create linkUtil Node with variables", function() {
          return expect(agent.get('linkUtil')[0]).to.exist;
        });
        it("should create sensory node with variable", function() {
          return expect(agent.get('linkUtil')[0].get('d')).is.above(0.1 - 0.01).and.below(0.1 + 0.01).and.is.not.equal(0.1);
        });
        return it("should create sensory node with variable trough parameters", function() {
          var agent1;

          agent1 = new Agent({
            'linkUtil': [
              {
                'd': 4,
                'v': 1
              }, {
                'd': 6,
                'v': 2
              }
            ]
          });
          expect(agent1.get('linkUtil')[0].get('d')).is.above(4 - 1).and.below(4 + 1).and.is.not.equal(4);
          return expect(agent1.get('linkUtil')[1].get('d')).is.above(6 - 2).and.below(6 + 2).and.is.not.equal(6);
        });
      });
      describe("linkProbs", function() {
        it("should create linkProbs", function() {
          return expect(agent.get('linkProbs')).to.exist;
        });
        it("should create linkProbs with full parameters", function() {
          var agent2;

          agent2 = new Agent({
            'linkProbs': [0.2, 0.8]
          });
          expect(agent2.get('linkProbs')[0]).is.below(0.35);
          return expect(agent2.get('linkProbs')[1]).is.above(0.65);
        });
        return it("should mutate Utility and Probabilities on mutate()", function() {
          var varP0, varP1, varU0, varU1;

          varU0 = agent.get('linkUtil')[0].get('d');
          varU1 = agent.get('linkUtil')[1].get('d');
          varP0 = agent.get('linkProbs')[0];
          varP1 = agent.get('linkProbs')[1];
          agent.mutate();
          expect(agent.get('linkUtil')[0].get('d')).is.not.equal(varU0);
          expect(agent.get('linkUtil')[1].get('d')).is.not.equal(varU1);
          expect(agent.get('linkProbs')[0]).is.not.equal(varP0);
          return expect(agent.get('linkProbs')[1]).is.not.equal(varP1);
        });
      });
      return describe("act", function() {
        return it("should work", function() {
          return expect(agent.act()).to.match(/^eat$|^do not eat$/);
        });
      });
    });
  });

  describe("Environment", function() {
    var environment;

    environment = null;
    beforeEach(function() {
      return environment = new Environment();
    });
    afterEach(function() {
      return environment = null;
    });
    it('should exist', function() {
      return expect(environment).to.exist;
    });
    it('should create agents', function() {
      return expect(environment.get('agents')).to.exist;
    });
    it('should be able to use spawn with no params', function() {
      var spy;

      spy = sinon.spy(environment, "spawnAgent");
      environment.spawnAgent();
      expect(spy.called).is["true"];
      return expect(environment.get('agents').length).to.equal(1);
    });
    return describe('spawn', function() {
      var agents;

      agents = null;
      beforeEach(function() {
        environment.spawnAgent({
          'linkUtil': [
            {
              'd': 0.1,
              'v': 0.1
            }, {
              'd': 0.1,
              'v': 0.1
            }
          ],
          'linkProbs': [0.1, 0.9],
          'healthPoints': 25
        });
        return agents = environment.get('agents');
      });
      it('should create new agent', function() {
        return expect(agents.length).to.equal(1);
      });
      it('should update linkUtil', function() {
        return expect(agents.at(0).get('linkUtil')[0].get('d')).is.above(0.1 - 0.11).and.below(0.1 + 0.1).and.is.not.equal(0.1);
      });
      it('should update linkProbs', function() {
        expect(agents.at(0).get('linkProbs')[0]).is.below(0.30);
        return expect(agents.at(0).get('linkProbs')[1]).is.above(0.70);
      });
      it('should not create new agents after population cap', function() {
        var index, _i;

        for (index = _i = 1; _i <= 7; index = ++_i) {
          environment.spawnAgent();
        }
        return expect(agents.length).to.equal(5);
      });
      it('should be able to handle JSON string "spawnAgent(JSON.parse(Agent.pullEsseceInJSON()))"', function() {
        environment.spawnAgent(JSON.parse(agents.at(0).pullEsseceInJSON()));
        expect(agents.length).to.equal(2);
        expect(agents.at(1).get('healthPoints')).is.equal(agents.at(1).get('startingHealthPoints'));
        expect(agents.at(1).get('linkUtil')[0].get('d')).is.above(0.1 - 0.11).and.below(0.1 + 0.1).and.is.not.equal(0.1);
        expect(agents.at(1).get('linkProbs')[0]).is.below(0.35).and.is.not.equal(agents.at(0).get('linkProbs')[0]);
        return expect(agents.at(1).get('linkProbs')[1]).is.above(0.65).and.is.not.equal(agents.at(0).get('linkProbs')[1]);
      });
      return it('should be able to handle JSON string "spawnAgent(Agent.pullEsseceInJSON())"', function() {
        environment.spawnAgent(agents.at(0).pullEsseceInJSON());
        expect(agents.length).to.equal(2);
        expect(agents.at(1).get('healthPoints')).is.equal(agents.at(1).get('startingHealthPoints'));
        expect(agents.at(1).get('linkUtil')[0].get('d')).is.above(0.1 - 0.11).and.below(0.1 + 0.1).and.is.not.equal(0.1);
        expect(agents.at(1).get('linkProbs')[0]).is.below(0.35).and.is.not.equal(agents.at(0).get('linkProbs')[0]);
        return expect(agents.at(1).get('linkProbs')[1]).is.above(0.65).and.is.not.equal(agents.at(0).get('linkProbs')[1]);
      });
    });
  });

  describe('App', function() {
    it('should start', function() {
      var app;

      app = new App();
      expect(app.get('environment')).to.exist;
      return console.log(app);
    });
    return it('should ');
  });

}).call(this);
