// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Brain = (function(_super) {
    __extends(Brain, _super);

    function Brain() {
      _ref = Brain.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Brain.prototype.initialize = function() {
      return this.set('nodes', arguments.length && arguments[0]['nNodes'] ? new Nodes(arguments[0]) : new Nodes());
    };

    Brain.prototype.mutateNodes = function() {
      return this.nodes.forEach(function(node) {
        return node.mutate();
      });
    };

    return Brain;

  })(Backbone.Model);

}).call(this);
