// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Environment = (function(_super) {
    __extends(Environment, _super);

    function Environment() {
      _ref = Environment.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Environment.prototype.initialize = function() {
      return this.set('Agents', new Agents());
    };

    return Environment;

  })(Backbone.Model);

}).call(this);
