// Generated by CoffeeScript 1.6.2
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Environment = (function(_super) {
    __extends(Environment, _super);

    function Environment() {
      _ref = Environment.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Environment.prototype.initialize = function() {
      this.set('populationLimit', 5);
      return this.set('agents', new Agents());
    };

    Environment.prototype.spawnAgent = function() {
      if (this.get('agents').length < this.get('populationLimit')) {
        if (arguments.length) {
          return this.get('agents').add(arguments[0]);
        } else {
          return this.get('agents').add([{}]);
        }
      } else {
        return void 0;
      }
    };

    return Environment;

  })(Backbone.Model);

}).call(this);
